-module(grisp_cryptoauth_known_certs).

-export([test_intermediate/0,
         test_root/0]).


test_intermediate() ->
<<"-----BEGIN CERTIFICATE-----
MIIB4DCCAUKgAwIBAgIBATAKBggqhkjOPQQDAjAPMQ0wCwYDVQQDDARyb290MB4X
DTIxMDkwNjE1MjI0NloXDTMxMDkwNDE1MjI0NlowFzEVMBMGA1UEAwwMaW50ZXJt
ZWRpYXRlMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIeo35aTGFRmCqt5OFW2w
gQcp+70HVWCOCjaBFmjAjX8dw/RyzWXms03geoNuxRWdLaJwOy47g/77AIOzz/+N
pKOBhjCBgzAMBgNVHRMEBTADAQH/MDgGA1UdIwQxMC+AFIBiOcLn0SzD6WGK3kb2
v1PELACpoROkETAPMQ0wCwYDVQQDDARyb290ggID6TAdBgNVHQ4EFgQUF9xB8fry
mlABcPuzG6wTy8YwAHkwGgYDVR0RBBMwEYIJbG9jYWxob3N0hwR/AAABMAoGCCqG
SM49BAMCA4GLADCBhwJBfKts5a35296qf2KT+1Tl21Cxy+1+JQoAgAmFjtAbJMTx
RTi3ZRXB31J86iihcAkXSCCqti7pBM85iHmIQ+v1kYgCQgH2HjDkpJrdgh3WoWyy
EvHPxWQkWn4hQONSMu4lCY8R0tsJr0m4U+sVJs+GrxmiaEmrcjWO55x9IwGZBxuM
GVh3ZQ==
-----END CERTIFICATE-----">>.


test_root() ->
<<"-----BEGIN CERTIFICATE-----
MIIBxTCCASagAwIBAgICA+kwCgYIKoZIzj0EAwQwDzENMAsGA1UEAwwEcm9vdDAe
Fw0yMTA5MDYxNDM4NDdaFw0zMTA5MDQxNDM4NDdaMA8xDTALBgNVBAMMBHJvb3Qw
gZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAAQMoI+iiMGism31sf1FEb8OuPHa8wU
pW/2NrWYv/YT1cnWLZe5hHDPtKI5dAKUBqcq++pRIFRnazn5aRBP1MQR/AFFa37P
/ZKhAqAEmr6FwEOzwjA0U49HThwxnHV3lniSSFVCRN8CRjxwSInPir0ePm/PGiUx
T3Dc9mZJUVLuRwOL3qMvMC0wDAYDVR0TBAUwAwEB/zAdBgNVHQ4EFgQUgGI5wufR
LMPpYYreRva/U8QsAKkwCgYIKoZIzj0EAwQDgYwAMIGIAkIAzdapf3mcDgqmVL14
QeyU6znQ4HAbamGZ/Wmtna9YqLE4yiW51XsP0GyoE88MuIg8t7EIA/vKbeHrRh3/
BHFhpUwCQgHRVfE6u0gHnpD6CIixVnUSIwM1efJDT6lS97t9jxeIay+/bI/qlOsA
GDCzjWfZOruibQxfp43HonaQ4OZkfwpkaQ==
-----END CERTIFICATE-----">>.
